### ISSUE TITLE
As a user, I want to provision AWS resource and time ETL 3.5M nodes into stellar-search 

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-search#63]
Ansible script to provision & run stellar-search in AWS.

- Roles of 3 node cluster in ElasticSearch, Spring App, Postgres, Kabana & x-pack (free trial) 
- Assume Stackoverflow data is uploaded to AWS storage
- 32 GB RAM on each node of ElasticSearch
- constrain the resource of all ElasticSearch instance 

# AC
- Able to automatically provision entire stellar-search in AWS
- Note time to load

**Comment by gaj67** [comment]
Started learning Ansible and YAML. Got ansible playbook working for dynamically creating an EC2 machine.

Terry recommended switching effort over to learning Vagrant to provision ElasticSearch prior to trying to do the same for AWS. Terry has created 3 small EC2 nodes for (later) testing ES provisioning on AWS.
