### ISSUE TITLE
Improve performance to upcert process in Elastic - Postgres

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-search#65]
@chinkitp commented on [Wed May 02 2018](https://github.com/data61/stellar-storage-eval/issues/20)

Assumption: All nodes and edges have been loaded into Postgres

Reading from Postgres we aim to generate the entire node document with the in & out edges in memory. We will then load the document into Elasticsearch, therefore avoiding the upcert and scripting. 

## AC 
- [Done] implement change to stellar-search to generate entire node document in memory by reading the nodes and edges from the Postgres database
- switch off the mapping of all fields during bulk ingest 
- implement the reindex endpoint to switch on the indexing of all fields 
- parallelise the load into elastic using all available CPUs
- (optional)  demonstrate the elasticsearch is throttling client requests.

**Comment by chinkitp** [comment]
After discussions - we should try to tweak Elastic before going down this path.

**Comment by chinkitp** [comment]
We have tried to _Tune Elastic to improve performance_ #68 and discovered that using postgres as temporary storage and building the entire document outside elastic will give the best performance.

**Comment by bowernj** [comment]
Timings for step2 ingest with stellar-search 

AWS server architecture:
1x | stellar-search + postgres | m5.xlarge 16GB
3x | elasticsearch | m5.2xlarge 32GB 

Attempt 1:
step2 w/ 20GB volume = 124 minutes. Ran out of burst credits during postgres ingest and write speed became very slow.

Attempt 2:
step2 w/ 1TB gp2 EBS volume (3K IOPS baseline) = 82 minutes

Attempt 3:
step2 w/ 1TB and postgres settings =  52 minutes

```
shared_buffers: 3GB
maintenance_work_mem: 500MB
work_mem: 16MB
max_wal_size: 1GB
effective_cache_size: 2GB
synchronous_commit: "off"
fsync: "off"
full_page_writes: "off"
```
