### ISSUE TITLE
bulk load nodes & edges into postgres to assist the ingest process

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-search#70]
The aim is to dynamically create temporary storage space for nodes and edges (indexed) and bulk load the ingest files into these tables. The method of loading data into Postgres needs to be optimised for bulk load. Suggest using methods that work under the ORM layer eg. 

- https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html 
- http://jdbi.org/jdbi2/

create node & edge tables dynamically (as they can be dropped once the ingest process is completed)

- Pre-load raw data into Postgres so that related edges are indexed and can be selected quickly (to generate and insert the node-centric document into elastic in one operation). Use node and edge tables and index the node id columns only. Put postgres into read-only mode after creating temporary db/tables so that read-locks aren't taken. This should be significantly faster than incremental updates to documents in elastic.

## AC
- stellar-search modified to bulk load nodes & edges into Postgres
- all nodes and edges loaded into postgres table
- post loading of the rows create a non-clustered index on source & target column of the edges

**Comment by gaj67** [comment]
Working branch in feature/70-postgres-edges

**Comment by gaj67** [comment]
Actually, this version is still faulty, in that an error during ingestion into Postgres will leave the table(s) intact, precluding the operation being repeated.
