### ISSUE TITLE
performance test loading Folder 1 in AWS for stellar search

### ISSUE THREAD

**Issue by chinkitp** [data61/stellar-search#72]
so from the feature build deploy stellar-search into AWS
make code changes into stellar-search to switch off loading into Elastic
ensure you have 120GB 
download from S3 Folder 1
ingest nodes & edges (without the adjacency) into Postgres 

Please see https://github.com/data61/stellar-search/blob/develop/ansible/README.md for assistance

## AC 
- time the load early in the Sprint
- provide input to #70

**Comment by bowernj** [comment]
4 minutes to ingest step2
